services:
  ui-prod:
    build:
      context: electron-ui
      dockerfile: Dockerfile.prod
    container_name: ui-prod
    ports:
      - "5173:5173"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - gym-pro

  db:
    build:
      context: db
      dockerfile: Dockerfile
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CoolPass321
      POSTGRES_DB: gym_pro
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - gym-pro

  db-api:
    build:
      context: db-api
      dockerfile: Dockerfile
    container_name: db-api
    ports:
      - "5431:5431"
    environment:
      FLASK_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: CoolPass321
      DB_NAME: gym_pro
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - gym-pro
  
  account-mgmt:
    build:
      context: account-mgmt
      dockerfile: Dockerfile
    container_name: account-mgmt
    ports:
      - "5320:5320"
    restart: unless-stopped
    networks:
      - gym-pro

  parking:
    build:
      context: parking
      dockerfile: Dockerfile
    container_name: parking
    ports:
      - "5428:5428"
    restart: unless-stopped
    networks:
      - gym-pro

  payment:
    build:
      context: payment
      dockerfile: Dockerfile
    container_name: payment
    ports:
      - "5427:5427"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: CoolPass321
      DB_NAME: gym_pro
      DB_API_INTERNAL: http://db-api:5431
      MEMBERSHIP_MODULE: http://membership-module:5211
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - gym-pro

  membership-module:
    build:
      context: membership-module
      dockerfile: Dockerfile
    container_name: membership-module
    ports:
      - "5211:5211"
    restart: unless-stopped
    networks:
      - gym-pro


networks:
  gym-pro:
    name: gym-pro

volumes:
  postgres_data:
    name: postgres_data
