FROM node:22-bookworm

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN npm install -g pnpm@9
RUN pnpm install --frozen-lockfile
RUN pnpm install -D @types/node

COPY . .

EXPOSE 5173

CMD ["pnpm", "exec", "vite", "--mode", "web", "--host", "0.0.0.0", "--port", "5173"]
