server {
    listen 5173;

    root /usr/share/nginx/html;
    index index.html;

    # SPA — send all non-asset requests to index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/db-api/pay {
        proxy_pass http://payment:5427;
    }

    location /api/db-api/ {
        proxy_pass http://db-api:5431;
    }

    location /api/account-mgmt/ {
        proxy_pass http://account-mgmt:5320;
    }

    location /api/ {
        proxy_pass http://membership-module:5211;
    }
}
